### ISSUE TITLE
Modified posts push error

### ISSUE THREAD

**Issue by JerryBian** [JerryBian/swan#44]
Local pushed posts trigger GitHub webhooks, it returned exception.

We need to investigate.

**Comment by JerryBian** [comment]
Caught exception from journalctl

```sh
Laobian.Share.BlogEngine.Parser.AssetParseException: Exception of type 'Laobian.Share.BlogEngine.Parser.AssetParseException' was thrown.
Oct 16 14:28:51:    at Laobian.Share.BlogEngine.Parser.BlogAssetParser.FromTextAsync(String requestText, String nameValueSplitter, String lineSplitter) in \\mac\iCloud\github\la
Oct 16 14:28:51:    at Laobian.Share.BlogEngine.Parser.BlogPostParser.FromTextAsync(String text, String link) in \\mac\iCloud\github\laobian\source\src\share\BlogEngine\Parser\B
Oct 16 14:28:51:    at Laobian.Share.BlogEngine.BlogService.GetPostsFromFileAsync() in \\mac\iCloud\github\laobian\source\src\share\BlogEngine\BlogService.cs:line 238
Oct 16 14:28:51:    at Laobian.Share.BlogEngine.BlogService.UpdateMemoryPostsAsync() in \\mac\iCloud\github\laobian\source\src\share\BlogEngine\BlogService.cs:line 203
Oct 16 14:28:51:    at Laobian.Share.BlogEngine.BlogService.UpdateMemoryAssetsAsync(Boolean cloneFirst) in \\mac\iCloud\github\laobian\source\src\share\BlogEngine\BlogService.cs
Oct 16 14:28:51:    at Laobian.Blog.Controllers.GitHubController.Hook() in \\mac\iCloud\github\laobian\source\src\blog\Controllers\GitHubController.cs:line 94
Oct 16 14:28:51:    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor exec
Oct 16 14:28:51:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 acti
Oct 16 14:28:51:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTas
Oct 16 14:28:51:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Oct 16 14:28:51:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Oct 16 14:28:51:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, St
Oct 16 14:28:51:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scop
Oct 16 14:28:51:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Oct 16 14:28:51:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Oct 16 14:28:51:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Sco
Oct 16 14:28:51:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
Oct 16 14:28:51:    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Oct 16 14:28:51:    at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
Oct 16 14:28:51:    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
Oct 16 14:28:51: warn: Laobian.Blog.Startup[0]
Oct 16 14:28:51:       Request error occurred.
```

**Comment by JerryBian** [comment]
Caught exception

```sh
Laobian.Share.BlogEngine.Parser.AssetParseException: Exception of type 'Laobian.Share.BlogEngine.Parser.AssetParseException' was thrown.
Oct 16 14:28:51 sp blog.laobian.me[2378]:    at Laobian.Share.BlogEngine.Parser.BlogAssetParser.FromTextAsync(String requestText, String nameValueSplitter, String lineSplitter) in \\mac\iCloud\github\laobian\source\src\share\BlogEngine\Parser\BlogAssetParser.cs:line 32
Oct 16 14:28:51 sp blog.laobian.me[2378]:    at Laobian.Share.BlogEngine.Parser.BlogPostParser.FromTextAsync(String text, String link) in \\mac\iCloud\github\laobian\source\src\share\BlogEngine\Parser\BlogPostParser.cs:line 36
Oct 16 14:28:51 sp blog.laobian.me[2378]:    at Laobian.Share.BlogEngine.BlogService.GetPostsFromFileAsync() in \\mac\iCloud\github\laobian\source\src\share\BlogEngine\BlogService.cs:line 238
Oct 16 14:28:51 sp blog.laobian.me[2378]:    at Laobian.Share.BlogEngine.BlogService.UpdateMemoryPostsAsync() in \\mac\iCloud\github\laobian\source\src\share\BlogEngine\BlogService.cs:line 203
Oct 16 14:28:51 sp blog.laobian.me[2378]:    at Laobian.Share.BlogEngine.BlogService.UpdateMemoryAssetsAsync(Boolean cloneFirst) in \\mac\iCloud\github\laobian\source\src\share\BlogEngine\BlogService.cs:line 158
Oct 16 14:28:51 sp blog.laobian.me[2378]:    at Laobian.Blog.Controllers.GitHubController.Hook() in \\mac\iCloud\github\laobian\source\src\blog\Controllers\GitHubController.cs:line 94
Oct 16 14:28:51 sp blog.laobian.me[2378]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Oct 16 14:28:51 sp blog.laobian.me[2378]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
Oct 16 14:28:51 sp blog.laobian.me[2378]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Oct 16 14:28:51 sp blog.laobian.me[2378]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Oct 16 14:28:51 sp blog.laobian.me[2378]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Oct 16 14:28:51 sp blog.laobian.me[2378]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Oct 16 14:28:51 sp blog.laobian.me[2378]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Oct 16 14:28:51 sp blog.laobian.me[2378]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Oct 16 14:28:51 sp blog.laobian.me[2378]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Oct 16 14:28:51 sp blog.laobian.me[2378]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Oct 16 14:28:51 sp blog.laobian.me[2378]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
Oct 16 14:28:51 sp blog.laobian.me[2378]:    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Oct 16 14:28:51 sp blog.laobian.me[2378]:    at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
Oct 16 14:28:51 sp blog.laobian.me[2378]:    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
Oct 16 14:28:51 sp blog.laobian.me[2378]: warn: Laobian.Blog.Startup[0]
Oct 16 14:28:51 sp blog.laobian.me[2378]:       Request error occurred.
```
